services:
  mysql:
    env_file:
      - .env
    image: mysql:8.4
    container_name: dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    restart: always

  app:
    image: maeum:dev
    container_name: dev-maeum
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  mysql_data: